import 'nue-ui-iconfont/dist/iconfont.css'
import 'nue-ui-theme-shadlike/dist/index.css'

import './animation.css'
import './variables.css'

import './avatar.css'
import './badge.css'
import './button.css'
import './collapse.css'
import './confirm.css'
import './container.css'
import './dialog.css'
import './div.css'
import './drawer.css'
import './dropdown.css'
import './icon.css'
import './input.css'
import './link.css'
import './prompt.css'
import './textarea.css'
import './tooltip.css'

