export const PROJECT_CREATOR_DIALOG_KEY = 'project-creator-dialog'
export const PROJECT_MANAGER_DIALOG_KEY = 'project-manager-dialog'
export const PROJECT_UPDATER_DIALOG_KEY = 'project-updater-dialog'
export const TAG_COLOR_UPDATER_DIALOG_KEY = 'tag-color-updater-dialog'
export const TAG_CREATOR_DIALOG_KEY = 'tag-creator-dialog'
export const TAG_MANAGER_DIALOG_KEY = 'tag-manager-dialog'
export const TAG_UPDATER_DIALOG_KEY = 'tag-updater-dialog'
export const TASK_CREATOR_DIALOG_KEY = 'task-creator-dialog'
export const TASK_REMINDER_DIALOG_KEY = 'task-reminder-dialog'
export const PARENT_TASK_SELECTOR_DIALOG_KEY = 'parent-task-selector-dialog'
export const POMODORO_TIMER_SETTING_DIALOG_KEY = 'pomodoro-timer-setting-dialog'
export const POMODORO_CREATOR_DIALOG_KEY = 'pomodoro-creator-dialog'
export const POMODORO_UPDATER_DIALOG_KEY = 'pomodoro-updater-dialog'

