export const BUILT_IN_PROJECT_VIEW_CONTEXT_KEY = 'BUILT_IN_PROJECT_VIEW_CONTEXT_KEY'
export const PROJECT_VIEW_CONTEXT_KEY = 'PROJECT_VIEW_CONTEXT_KEY'
export const TAG_VIEW_CONTEXT_KEY = 'TAG_VIEW_CONTEXT_KEY'