/**
 * 任务领域错误码
 * @description 领域层只产出稳定错误码，不产出面向用户的文案。
 *              文案翻译由 presentation 层负责（见 presentation/task/utils/error-message.ts），
 *              以保证领域层零框架依赖（不依赖 vue-i18n）。
 */
export const TaskErrorCode = {
    // 名称
    NAME_EMPTY: 'TASK_NAME_EMPTY',
    NAME_TOO_LONG: 'TASK_NAME_TOO_LONG',
    // 描述
    DESC_TOO_LONG: 'TASK_DESC_TOO_LONG',
    // 枚举
    STATE_INVALID: 'TASK_STATE_INVALID',
    PRIORITY_INVALID: 'TASK_PRIORITY_INVALID',
    REMIND_REPEAT_INVALID: 'TASK_REMIND_REPEAT_INVALID',
    // 时间
    REMIND_TIME_FORMAT_INVALID: 'TASK_REMIND_TIME_FORMAT_INVALID',
    REMIND_AT_INVALID: 'TASK_REMIND_AT_INVALID',
    START_AT_INVALID: 'TASK_START_AT_INVALID',
    END_AT_INVALID: 'TASK_END_AT_INVALID',
    START_AFTER_END: 'TASK_START_AFTER_END',
    GIVEN_UP_AT_INVALID: 'TASK_GIVEN_UP_AT_INVALID',
    GIVEN_UP_BEFORE_START: 'TASK_GIVEN_UP_BEFORE_START',
    STAR_MARK_AT_INVALID: 'TASK_STAR_MARK_AT_INVALID',
    STAR_MARK_FORBIDDEN: 'TASK_STAR_MARK_FORBIDDEN',
    SCHEDULE_FORBIDDEN: 'TASK_SCHEDULE_FORBIDDEN',
    TASK_NOT_FOUND: 'TASK_NOT_FOUND',
    // 稍后提醒
    SNOOZE_DURATION_NOT_INTEGER: 'TASK_SNOOZE_DURATION_NOT_INTEGER',
    SNOOZE_DURATION_OUT_OF_RANGE: 'TASK_SNOOZE_DURATION_OUT_OF_RANGE',
    // 关联任务
    TASK_ID_EMPTY: 'TASK_ID_EMPTY',
    // 检查事项
    CHECK_ITEM_NAME_EMPTY: 'TASK_CHECK_ITEM_NAME_EMPTY',
    CHECK_ITEM_NAME_TOO_LONG: 'TASK_CHECK_ITEM_NAME_TOO_LONG',
    CHECK_ITEM_SORT_ID_NEGATIVE: 'TASK_CHECK_ITEM_SORT_ID_NEGATIVE',
    CHECK_ITEM_NOT_FOUND: 'TASK_CHECK_ITEM_NOT_FOUND',
    // 评论
    COMMENT_CONTENT_EMPTY: 'TASK_COMMENT_CONTENT_EMPTY',
    COMMENT_CONTENT_TOO_LONG: 'TASK_COMMENT_CONTENT_TOO_LONG'
} as const

// 任务领域错误码取值
export type TaskErrorCodeValue = (typeof TaskErrorCode)[keyof typeof TaskErrorCode]